# Generated by Django 3.1.1 on 2020-09-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setquestions', '0002_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
    ]
