# Generated by Django 3.1.1 on 2020-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setquestions', '0003_auto_20200925_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_checked',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
