# Generated by Django 3.1.1 on 2020-09-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setquestions', '0005_auto_20200925_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct_ans',
            field=models.CharField(default='', max_length=200),
        ),
    ]
