# Generated by Django 3.1.1 on 2020-09-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setquestions', '0006_choice_correct_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='correct_ans',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(default='', max_length=200),
        ),
    ]
