# Generated by Django 3.1.1 on 2020-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setquestions', '0007_auto_20200925_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
