# Generated by Django 3.1.1 on 2020-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setquestions', '0008_question_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.FloatField(default=0),
        ),
    ]
