# Generated by Django 3.1.1 on 2020-09-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setquestions', '0013_choice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.CharField(default='unchecked', max_length=100)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setquestions.choice')),
            ],
        ),
    ]
