# Generated by Django 3.1.1 on 2020-09-22 17:14

import assignment.models
import assignment.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(default=assignment.models._createId, max_length=200, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='activity/')),
                ('index', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('header', models.CharField(choices=[('graded', 'graded'), ('ungraded', 'ungraded')], max_length=50)),
                ('q_number', models.IntegerField()),
                ('activity', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('date_submitted', models.DateTimeField(default=assignment.utils.Utils.get_date_time)),
                ('date_created', models.DateTimeField(default=assignment.utils.Utils.get_date_time)),
                ('course', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.CharField(default=assignment.models._createId, max_length=200, primary_key=True, serialize=False)),
                ('courses', models.CharField(max_length=200, verbose_name='Course name')),
                ('choose_back_color', models.CharField(default='black', max_length=200, verbose_name='Course background')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('', 'select semester'), ('semester one', 'SEMESTER ONE'), ('semester two', 'SEMESTER TWO')], max_length=100, verbose_name='semester')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOtherCourse',
            fields=[
                ('id', models.CharField(default=assignment.models._createId, max_length=200, primary_key=True, serialize=False)),
                ('choose_course', models.CharField(max_length=200)),
                ('selectcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.selectcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.CharField(default=assignment.models._createId, max_length=200, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='activity/')),
                ('file_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=assignment.utils.Utils.get_date_time)),
                ('course', models.CharField(max_length=200)),
                ('submission_date', models.DateField(default=assignment.utils.Utils.get_date_time)),
                ('attach_info', models.TextField(blank=True)),
                ('selectcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.selectcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.CharField(default=assignment.models._createId, max_length=200, primary_key=True, serialize=False)),
                ('q_number', models.IntegerField()),
                ('title', models.CharField(choices=[('', 'select activity'), ('Assignments', 'Assignments'), ('Exercises', 'Exercises'), ('Quizzes', 'Quizzes')], max_length=50)),
                ('status', models.CharField(choices=[('', 'select status'), ('graded', 'graded'), ('not graded', 'not graded')], max_length=50)),
                ('scored', models.FloatField(verbose_name='score')),
                ('total', models.FloatField()),
                ('course', models.CharField(max_length=200)),
                ('marker', models.CharField(max_length=200)),
                ('date_graded', models.DateField(default=assignment.utils.Utils.get_date)),
                ('date_graded1', models.DateTimeField(default=assignment.utils.Utils.get_date_time)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('studentothercourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.studentothercourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='selectcourse',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.semester'),
        ),
        migrations.AddField(
            model_name='selectcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegisterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('', 'Select a course'), ('Integral Equations', 'Integral Equations'), ('Real Functions', 'Real Functions')], max_length=100)),
                ('class_or_level', models.CharField(choices=[('', 'Select class'), ('Math1', 'Math 1'), ('Math2', 'Math 2'), ('Math3', 'Math 3'), ('Math4', 'Math 4')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChooseActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='chooseactivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.chooseactivity'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='studentothercourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.studentothercourse'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
