# Generated by Django 3.1.1 on 2020-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='title',
            field=models.CharField(choices=[('', 'select activity'), ('Assignments', 'Assignments'), ('Exercises', 'Exercises'), ('Quizzes', 'Quizzes'), ('Trial Works', 'Trial Works')], max_length=50),
        ),
    ]
